eShop/urls.py

from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView





urlpatterns = [

    path('admin/', admin.site.urls),
    
    path('shop/', include('shop.urls')),
    path('register/', include('register.urls')),
    
    path('', include("django.contrib.auth.urls")),
    
    path("", TemplateView.as_view(template_name="home.html"), name="home"),



    

    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


shop/urls.py
from django.urls import path
from . import views

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Namespace
app_name = 'shop'


urlpatterns = [



    path('', views.HomeView.as_view(), name='home'),

    path('products/', views.products, name="products"),

    path('filtered_products/', views.filtered_products, name='filtered_products'),
    
    path('recommend/', views.recommend_products, name='recommend_products'),

    path('rate-product/<slug:name>/', views.rate_product, name='rate_product'),
    
    path('productDetails/<path:name>/', views.productDetails, name='productDetails'),
    
    path('cart/', views.cart, name='cart'),
    path('add_to_cart/<path:name>/', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<path:name>/', views.remove_from_cart, name='remove_from_cart'),


]

urlpatterns += staticfiles_urlpatterns()


templates/home.html
<!-- templates/home.html-->
{% extends "./layout.html" %}


{% block title %}Home{% endblock %}

<div class="navBar">
  {% block navBar %}navBar{% endblock %}
</div>
{% block content %}
<h1>Welcome to the eShop</h1>

{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}

templates/layout.html
{% load static %}

<html>

<head>
    <!-- Add these lines to include Bootstrap CSS and JavaScript -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>


    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">


</head>

<body>
    <!-- navBar.html -->


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'shop:cart' %}">Cart</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'shop:products' %}">Products</a>

                </ul>

                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text">Hello, {{ user.username }}!</span>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'home' %}?next=/">Log out</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                    {% endif %}

                </ul>
            </div>
        </div>
    </nav>







    <div id="content" name="content">
        {% block content %}

        {% endblock %}
    </div>
</body>

</html>