eShop/urls.py

from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView





urlpatterns = [

    path('admin/', admin.site.urls),
    
    path('shop/', include('shop.urls')),
    path('register/', include('register.urls')),
    
    path('', include("django.contrib.auth.urls")),
    
    path("", TemplateView.as_view(template_name="home.html"), name="home"),



    

    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


shop/urls.py
from django.urls import path
from . import views

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Namespace
app_name = 'shop'


urlpatterns = [



    path('', views.HomeView.as_view(), name='home'),

    path('products/', views.products, name="products"),

    path('filtered_products/', views.filtered_products, name='filtered_products'),
    
    path('recommend/', views.recommend_products, name='recommend_products'),

    path('rate-product/<slug:name>/', views.rate_product, name='rate_product'),
    
    path('productDetails/<path:name>/', views.productDetails, name='productDetails'),
    
    path('cart/', views.cart, name='cart'),
    path('add_to_cart/<path:name>/', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<path:name>/', views.remove_from_cart, name='remove_from_cart'),


]

urlpatterns += staticfiles_urlpatterns()


shop/models.py
from django.db import models
from django.contrib.auth.models import User

from django.utils.text import slugify

# ADDED TO DEAL WITH SLUG ISSUES
class YourModel(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)



class Category(models.Model):
    name = models.SlugField(max_length=255, unique=True)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = "Categories"
        
class Product(models.Model):
    name = models.SlugField(max_length=255, unique=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images', null=True)
    features = models.JSONField(default=dict)  
    average_rating = models.DecimalField(max_digits=3, decimal_places=0, default=0)
    total_ratings = models.PositiveIntegerField(default=0)

    def update_average_rating(self):
        ratings = Rating.objects.filter(product=self)
        if ratings.exists():
            total_ratings = ratings.count()
            sum_ratings = sum(rating.rating for rating in ratings)
            average_rating = sum_ratings / total_ratings
            self.average_rating = round(average_rating, 2)
            self.total_ratings = total_ratings
        else:
            self.average_rating = 0
            self.total_ratings = 0
        self.save()

    def __str__(self):
        return f"{self.name} {self.description} {self.price} {self.category} {self.image} {self.average_rating}"

class Rating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='ratings')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.PositiveBigIntegerField(choices=((1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')), null=True)
    
    class Meta:
        unique_together = ('product', 'user')
    
    def __str__(self):
        return f"{self.user}'s {self.rating}-star rating for {self.product}"


    
    

class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    products = models.ManyToManyField('Product')

    def __str__(self):
        return f"Cart for {self.user.username}"
    
    

class UserInteraction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    action_type = models.CharField(max_length=20)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} {self.action_type} {self.product.name}"


    




shop/forms.py
from django import forms
from .models import Product, Rating


class ImageForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'description', 'price', 'category', 'image')
        
        


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ['rating']
        widgets = {
            'rating': forms.Select(attrs={'class': 'form-control'}),
        }

    def as_custom_widget(self):
        return self['rating'].as_widget()

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Product, Cart, Category, UserInteraction, Rating
from django.views.generic.list import ListView
from django.db.models import Q
from django.contrib.auth.decorators import login_required

class HomeView(ListView):
    model = Category
    template_name = 'eShop/templates/layout.html'
    
def products(request):
    categories = Category.objects.all()
    qs = Product.objects.all()
    context = {
        'objects' : qs,
        'categories': categories,
    }
    return render(request, "shop/products.html", context)

def productDetails(request, name):
    product = get_object_or_404(Product, name=name)
    context = {
        'object': product
    }

    # Create a UserInteraction instance for the 'view' action
    if request.user.is_authenticated:
        UserInteraction.objects.create(user=request.user, action_type='view', product=product)

    return render(request, "shop/productDetails.html", context)

def cart(request):
    if request.user.is_authenticated:
        cart, created = Cart.objects.get_or_create(user=request.user)
        user = request.user
        recommended_products = get_recommendations(user)
        return render(request, 'shop/cart.html', {'user': request.user, 'cart': cart, 'recommended_products': recommended_products,})
    else:
        return render(request, 'shop/cart.html', {'user': None, 'cart': None})

def add_to_cart(request, name):
    if request.user.is_authenticated:
        product = get_object_or_404(Product, name=name)
        cart, created = Cart.objects.get_or_create(user=request.user)
        cart.products.add(product)

        # Create a UserInteraction instance for the 'added_to_cart' action
        UserInteraction.objects.create(user=request.user, action_type='added_to_cart', product=product)

        return redirect('shop:cart')
    else:
        return redirect('login')

def remove_from_cart(request, name):
    if request.user.is_authenticated:
        product = get_object_or_404(Product, name=name)
        cart = get_object_or_404(Cart, user=request.user)
        cart.products.remove(product)
        return redirect('shop:cart')
    else:
        return redirect('login')  # Redirect to login page if the user is not authenticated

def filtered_products(request):
    selected_category = request.GET.get('category', '')
    search_query = request.GET.get('search', '')
    sort_by = request.GET.get('sort_by', '')
    order = request.GET.get('order', 'asc')

    products = Product.objects.all()

    # Filter by category if selected
    if selected_category:
        products = products.filter(category__name=selected_category)

    # Filter by search query if provided
    if search_query:
        products = products.filter(name__icontains=search_query)

    # Apply sorting based on the selected option and order
    if sort_by == 'rating':
        products = products.order_by(f'{"-" if order == "desc" else ""}average_rating')
    elif sort_by == 'price':
        products = products.order_by(f'{"-" if order == "desc" else ""}price')

    categories = Category.objects.values_list('name', flat=True).distinct()

    context = {
        'objects': products,
        'categories': categories,
        'selected_category': selected_category,
        'sort_by': sort_by,
        'order': order,
    }

    return render(request, 'shop/filtered_products.html', context)

def get_viewed_products(user):
    viewed_products = UserInteraction.objects.filter(user=user, action_type='view')
    cart_products = UserInteraction.objects.filter(user=user, action_type='added_to_cart')

    viewed_product_ids = set(action.product.id for action in viewed_products)
    cart_product_ids = set(action.product.id for action in cart_products)

    return list(viewed_product_ids - cart_product_ids)

def get_recommendations(user, top_n=3):
    viewed_product_ids = get_viewed_products(user)
    recent_viewed_products = UserInteraction.objects.filter(user=user, action_type='view', product__id__in=viewed_product_ids).order_by('-timestamp')[:top_n]

    return [action.product for action in recent_viewed_products]

@login_required
def recommend_products(request):
    user = request.user
    recommended_products = get_recommendations(user)

    context = {
        'recommended_products': recommended_products,
    }

    return render(request, 'shop/recommended_products.html', context)

def rate_product(request, name):
    if request.method == 'POST':
        product = get_object_or_404(Product, name=name)
        rating_value = int(request.POST.get('rating', 0))

        # Check if the user has already rated this product
        existing_rating = Rating.objects.filter(product=product, user=request.user).first()
        if existing_rating:
            existing_rating.rating = rating_value
            existing_rating.save()
        else:
            Rating.objects.create(product=product, user=request.user, rating=rating_value)

        # Update the average rating for the product
        product.update_average_rating()

    return redirect('shop:productDetails', name=name)

shop/templates/shop/cart.html
<!-- ADD LAYOUT -->
{% extends 'C:\Users\olive\Desktop\ACG Fall 2023\Internet Programming\eShopFinal\eShop\templates\layout.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Product Details</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
    </script>
</head>


<body>
    <div class="navBar">
        {% block navBar %}navBar{% endblock %}
    </div>

    {% block content %}
    <h1>Your Cart</h1>

    {% if user.is_authenticated %}
    {% if cart.products.all %}
    <ul>
        {% for product in cart.products.all %}
        <li>
            {{ product.name }} - ${{ product.price }}
            <div class="product-item-cart img">
                <img alt="" src="{{ product.image.url }}">
            </div>
            <form method="post" action="{% url 'shop:remove_from_cart' name=product.name %}">
                {% csrf_token %}
                <button type="submit">Remove from Cart</button>
            </form>
        </li>
        {% endfor %}
    </ul>



    
    {% else %}
    <p>Your cart is empty.</p>
    <a class="nav-link" href="{% url 'shop:products' %}">Find products to add Here</a>

    {% if recommended_products %}
    <div class="recommended-products">
        <h1>Recommended Products</h1>
        <div class="product-grid">
            {% for recommended_product in recommended_products %}
            <div class="product-item">
                <a href="{% url 'shop:productDetails' name=recommended_product.name %}" target="_self">
                    <div class="product-item img">
                        <img alt="" src="{{ recommended_product.image.url }}">
                    </div>
                    <h3>{{ recommended_product.name }} {{ recommended_product.category }}</h3>
                    <p>${{ recommended_product.price }}</p>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
    {% else %}
    {% endif %}

    {% endif %}
    {% else %}
    <p>Please log in to view your cart.</p>
    <a class="nav-link" href="{% url 'login' %}">Login</a>




    {% endif %}
    {% endblock %}

</body>


</html>

shop/templates/shop/filtered_products.html
{% extends 'C:\Users\olive\Desktop\ACG Fall 2023\Internet Programming\eShopFinal\eShop\templates\layout.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Filtered Products</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
    <div class="navBar">
        {% block navBar %}navBar{% endblock %}
    </div>

    {% block content %}

    <h1>Filtered Products:</h1>

    <div id="cat_search" name="cat_search">
        <!-- Category filter form -->
        <form method="get" action="{% url 'shop:filtered_products' %}">
            <label for="category">Filter by Category:</label>
            <select id="category" name="category">
                <option value="">All Categories</option>
                <!-- Add options dynamically based on your categories -->
                {% for category in categories %}
                <option value="{{ category }}">{{ category }}</option>
                {% endfor %}
            </select>
            <button type="submit">Filter</button>
        </form>
        <!-- Search Bar -->
        <form method="get" action="{% url 'shop:filtered_products' %}">
            <input type="text" name="search" placeholder="Search by name">
            <button type="submit">Search</button>
        </form>

    </div>


    <form method="get" action="{% url 'shop:filtered_products' %}">
        <label for="sort_by">Sort By:</label>
        <select name="sort_by">
            <option value="">Default</option>
            <option value="rating" {% if sort_by == 'rating' %}selected{% endif %}>Rating</option>
            <option value="price" {% if sort_by == 'price' %}selected{% endif %}>Price</option>
        </select>
    
        <label for="order">Order:</label>
        <select name="order">
            <option value="asc" {% if order == 'asc' %}selected{% endif %}>Ascending</option>
            <option value="desc" {% if order == 'desc' %}selected{% endif %}>Descending</option>
        </select>
        
        <button type="submit">Apply Sort</button>
    </form>

    {% if user.is_authenticated %}

    <!-- Display recommended products -->
    <form action="{% url 'shop:recommend_products' %}" method="post">
        {% csrf_token %}
        <button type="submit">Get Recommended Products</button>
    </form>
    {% endif %}

    <div class="product-container">
        <div class="product-grid">
            {% for object in objects %}
                <div class="product-item">
                    <a href="{% url 'shop:productDetails' name=object.name %}" target="_blank">
                        <div class="product-item img">
                            <img alt="" src="{{ object.image.url }}">
                        </div>
                        <h3>{{ object.name }} {{ object.category.name }}</h3>
                        <p>${{ object.price }}</p>
                        {% if object.average_rating > 0 %}
                        <p>{{ object.average_rating }} of 5 stars </p>
                        {% endif %}
                    </a>
                </div>
            {% empty %}
                <p>No objects found</p>
            {% endfor %}
        </div>
    </div>

    {% endblock %}

</body>

</html>

shop/templates/shop/productDetails.html
<!-- ADD LAYOUT -->
{% extends 'C:\Users\olive\Desktop\ACG Fall 2023\Internet Programming\eShopFinal\eShop\templates\layout.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Product Details</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
    </script>
</head>


<body>

    <div class="navBar">
        {% block navBar %}navBar{% endblock %}
    </div>
    
    {% block content %}

    <a href="{% url 'shop:products' %}" class="back-button">Back to Products</a>

    <div class="product-item-solo">
        <h3>{{ object.name }} {{ object.category }}</h3>
        <p>{{ object.description }} ${{ object.price }}</p>
        <div class="product-item-solo img">
            <img alt="" src="{{ object.image.url }}">
        </div>
    </div>

    <form method="post" action="{% url 'shop:add_to_cart' name=object.name %}">
        {% csrf_token %}
        <button type="submit" class="add_to_cart_button">Add to Cart</button>
    </form>

    {% if request.user.is_authenticated %}
    <p>Rate this product:</p>
    <form method="post" class="rate_product_form"action="{% url 'shop:rate_product' name=object.name %}">
        {% csrf_token %}
        <select name="rating">
            <option value="1">1 star</option>
            <option value="2">2 stars</option>
            <option value="3">3 stars</option>
            <option value="4">4 stars</option>
            <option value="5">5 stars</option>
        </select>
        <button type="submit">Submit Rating</button>
    </form>
    {% endif %}
    {% endblock %}

</body>

</html>

shop/templates/shop/products.html
{% extends 'C:\Users\olive\Desktop\ACG Fall 2023\Internet Programming\eShopFinal\eShop\templates\layout.html' %}

{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Products</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
    <div class="navBar">
        {% block navBar %}navBar{% endblock %}
    </div>


    {% block content %}

    <h1>Products:</h1>
    <!-- Category filter form -->

    <div id="cat_search" name="cat_search">
        <form method="get" action="{% url 'shop:filtered_products' %}">
            <label for="category">Filter by Category:</label>
            <select id="category" name="category">
                <option value="">All Categories</option>
                <!-- Add options dynamically based on your categories -->
                {% for category in categories %}
                <option value="{{ category }}">{{ category }}</option>
                {% endfor %}
            </select>
            <button type="submit">Filter</button>
        </form>
        <!-- Search Bar -->
        <form method="get" action="{% url 'shop:filtered_products' %}">
            <input type="text" name="search" placeholder="Search by name">
            <button type="submit">Search</button>
        </form>

    </div>

    <form method="get" action="{% url 'shop:filtered_products' %}">
        <label for="sort_by">Sort By:</label>
        <select name="sort_by">
            <option value="">Default</option>
            <option value="rating" {% if sort_by == 'rating' %}selected{% endif %}>Rating</option>
            <option value="price" {% if sort_by == 'price' %}selected{% endif %}>Price</option>
        </select>
    
        <label for="order">Order:</label>
        <select name="order">
            <option value="asc" {% if order == 'asc' %}selected{% endif %}>Ascending</option>
            <option value="desc" {% if order == 'desc' %}selected{% endif %}>Descending</option>
        </select>
        
        <button type="submit">Apply Sort</button>
    </form>

    {% if user.is_authenticated %}

    <!-- Display recommended products -->
    <form action="{% url 'shop:recommend_products' %}" method="post">
        {% csrf_token %}
        <button type="submit">Get Recommended Products</button>
    </form>
    {% endif %}





    <div class="product-container">
        <div class="product-grid">
            {% for object in objects %}
            <div class="product-item">
                <a href="{% url 'shop:productDetails' name=object.name %}" target="_self">
                    <div class="product-item img">
                        <img alt="" src="{{ object.image.url }}">
                    </div>
                    <h3>{{ object.name }} {{ object.category }}</h3>
                    <p>${{ object.price }}</p>
                    {% if object.average_rating > 0 %}
                    <p>{{ object.average_rating }} of 5 stars </p>
                    {% endif %}

                </a>
            </div>
            {% empty %}
            <p>No objects found</p>
            {% endfor %}
        </div>
    </div>

    {% endblock %}

</body>

</html>

shop/templates/shop/recommended_products.html
{% extends 'C:\Users\olive\Desktop\ACG Fall 2023\Internet Programming\eShopFinal\eShop\templates\layout.html' %}

<div class="navBar">
    {% block navBar %}navBar{% endblock %}
</div>
{% block content %}
    {% if recommended_products %}
        <div class="recommended-products">
            <h1>Recommended Products</h1>
            <div class="product-grid">
                {% for recommended_product in recommended_products %}
                    <div class="product-item">
                        <a href="{% url 'shop:productDetails' name=recommended_product.name %}" target="_self">
                            <div class="product-item img">
                                <img alt="" src="{{ recommended_product.image.url }}">
                            </div>
                            <h3>{{ recommended_product.name }} {{ recommended_product.category }}</h3>
                            <p>${{ recommended_product.price }}</p>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% else %}
        <p>No recommended products available.</p>
    {% endif %}
{% endblock %}